language: php

sudo: false

php:
  - '7.3'

before_script:
  - composer install --no-interaction --prefer-source 

script:
  - composer validate --no-check-all --strict
  - ./vendor/bin/php-cs-fixer fix lib --dry-run
  - ./vendor/bin/phpstan analyse --configuration=phpstan.neon
  - ./vendor/bin/phpunit
