dist: xenial

language: php

php:
  # - '7.4'
  - '8.1'

install:
  - composer install --no-interaction --prefer-source 

script:
  - composer validate --no-check-all --strict
  - ./vendor/bin/php-cs-fixer fix lib --dry-run
  - ./vendor/bin/phpstan analyse --configuration=phpstan.neon
  - ./vendor/bin/phpunit
