version: "3.8"
services:
    httpd:
        image: httpd:2.4-alpine
        restart: unless-stopped
        container_name: ghibliql-httpd
        ports:
            - 8080:80/tcp
        volumes:
            - "./:/var/www/ghibliql"
            - "./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
            - "./conf/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ghibliql-php
        ports:
            - 9000:9000/tcp
        environment:
            - GHIBLIAPI_URL=https://ghibliapi.vercel.app
            - REDIS_URL=redis://redis:6379
        volumes:
            - "./:/var/www/ghibliql"
            - "./conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro"
        working_dir: "/var/www/ghibliql"
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine
        restart: unless-stopped
        container_name: ghibliql-redis
        ports:
            - 6379:6379/tcp

networks:
    default:
        driver: bridge
