version: "3.7"
services:
    httpd:
        image: httpd:2.4.46
        restart: unless-stopped
        ports:
            - 8080:80/tcp
        volumes:
            - "./:/var/www/ghibliql"
            - "./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
            - "./conf/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9000:9000/tcp
        environment:
            - HEROKU_REDIS_AQUA_URL=redis://redis:6379
        volumes:
            - "./:/var/www/ghibliql"
            - "./conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro"
        depends_on:
            - redis

    redis:
        image: redis:6.0.9
        restart: unless-stopped
        ports:
            - 6379:6379/tcp

networks:
    default:
        driver: bridge
