# fly.toml file generated for ghibliql on 2023-02-25T11:37:42+01:00

app = "ghibliql"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_URL = "https://ghibliql.fly.dev"
PORT = 9000

[experimental]
  auto_rollback = true

[build]
  builder = "paketobuildpacks/builder:full"
  buildpacks = ["gcr.io/paketo-buildpacks/php"]
  [build.args]
    BP_PHP_VERSION="8.1.16"
    BP_PHP_SERVER="httpd"
    BP_PHP_WEB_DIR="public"

[[services]]
  http_checks = []
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
